sudo: required
dist: trusty
language: python
cache:
    - pip
    - apt

python:
    - 2.7
    - 3.5
    - 3.6

before_install:
  - apt-get install shellcheck

script:
  - shellcheck easybutton.sh
  - shellcheck ubuntu16/bootstrap.sh
  - shellcheck centos7/bootstrap.sh
