sudo: required
dist: trusty
language: python

python:
    - 2.7

before_install:
  - sudo apt-get install shellcheck

script:
  - shellcheck easybutton.sh
  - shellcheck ubuntu16/bootstrap.sh
  - shellcheck centos7/bootstrap.sh
